import React from 'react';
import { 
  BookOpen, 
  CheckCircle2, 
  Sparkles, 
  Code2, 
  FileText, 
  Terminal, 
  ShieldCheck, 
  ExternalLink,
  Layers,
  Award
} from 'lucide-react';

export const AboutView: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      
      {/* Hero */}
      <div className="p-8 rounded-2xl bg-gradient-to-b from-slate-900 via-slate-900/90 to-slate-950 border border-slate-800 shadow-xl space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-950 border border-cyan-800/60 text-cyan-300 text-xs font-medium">
          <BookOpen className="w-3.5 h-3.5 text-cyan-400" />
          <span>Documentation Engine</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          About Project Guide
        </h1>
        <p className="text-base text-slate-300 leading-relaxed max-w-2xl">
          Project Guide is an AI-powered documentation generator designed to bridge the gap between building software and writing great documentation. It automatically generates 10 structured sections and an industry-standard README.md file from simple project inputs.
        </p>
      </div>

      {/* The 10 Essential Sections */}
      <div className="p-6 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-4">
        <h2 className="text-lg font-bold text-white tracking-tight flex items-center gap-2">
          <Layers className="w-5 h-5 text-cyan-400" />
          <span>The 10 Built-In Documentation Sections</span>
        </h2>
        <p className="text-xs text-slate-400">
          Every project generated by Project Guide includes comprehensive coverage of these 10 domains:
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
          {[
            { title: '1. Project Overview', desc: 'Executive summary, vision, core goals, and primary problem solved.' },
            { title: '2. Problem Statement', desc: 'Analysis of existing pain points, manual friction, and the justification for the architecture.' },
            { title: '3. Features & Capabilities', desc: 'Granular breakdown of user workflows, security, and administrative utilities.' },
            { title: '4. Technology Stack', desc: 'Formatted markdown table breaking down languages, frameworks, DB, and tools.' },
            { title: '5. Installation Guide', desc: 'Prerequisites, repository cloning, database creation, and dependency installation.' },
            { title: '6. How to Run', desc: 'Commands to launch local servers, build production artifacts, and configure .env parameters.' },
            { title: '7. How to Use', desc: 'Step-by-step user walkthrough from authentication to everyday operation.' },
            { title: '8. Project Structure', desc: 'Clean ASCII folder tree with annotations for configuration, controllers, models, and assets.' },
            { title: '9. API / Module Information', desc: 'Table of endpoints, HTTP methods, controllers, parameters, and schema models.' },
            { title: '10. Future Scope', desc: 'Roadmap checklist for subsequent milestones, companion apps, and performance scaling.' },
          ].map((item, i) => (
            <div key={i} className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800/80 space-y-1">
              <span className="font-semibold text-slate-200">{item.title}</span>
              <p className="text-slate-400 text-[11px] leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Hackathon Evaluation Checklist */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-900 to-indigo-950/30 border border-slate-800 space-y-4">
        <div className="flex items-center gap-2">
          <Award className="w-5 h-5 text-amber-400" />
          <h2 className="text-lg font-bold text-white tracking-tight">
            Hackathon & Production Quality Checklist
          </h2>
        </div>
        <p className="text-xs text-slate-300">
          Judges and open-source contributors heavily value clean onboarding. Project Guide ensures your project meets the highest standards:
        </p>

        <div className="space-y-2.5 text-xs text-slate-300">
          <div className="flex items-start gap-2.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
            <span><strong>Reproducible Run Instructions:</strong> Explicit commands so any evaluator can start your project in under 2 minutes.</span>
          </div>
          <div className="flex items-start gap-2.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
            <span><strong>Visual Architecture & Tree:</strong> Clear directory hierarchy so code reviewers instantly grasp file responsibilities.</span>
          </div>
          <div className="flex items-start gap-2.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
            <span><strong>Defensive Validation & API Docs:</strong> Documented endpoint schemas and request payloads.</span>
          </div>
          <div className="flex items-start gap-2.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
            <span><strong>GitHub-Ready README.md:</strong> Formatted with shields badges, tables, and standard open-source licensing.</span>
          </div>
        </div>
      </div>

    </div>
  );
};
